### ISSUE TITLE
Database structure creation

### ISSUE THREAD

**Issue by gabviv73** [cirrax/puppet-postfixadmin#6]
It can be useful to create the database structure running something like:

`curl -s  http://10.11.12.110/setup.php > /dev/null`

And let `postfixadmin-cli` task dependant on the DB to be ready.
I you agree, I can try to write something about this...

**Comment by trefzer** [comment]
This is a onetime task to initailize the db. Even on upgrade or host change you do not need to do so.
I do not think that this is worth some code (as long as you're not installing a new postfixadmin host every week !)
But I'm open for pull request !
