### ISSUE TITLE
puppet-mysql warning

### ISSUE THREAD

**Issue by gabviv73** [cirrax/puppet-postfixadmin#7]
It seems that it does not harm anything, but I always get this warning:

````
Warning: Unknown variable: 'mysql::params::exec_path'. (file: /etc/puppetlabs/code/environments/production/modules/mysql/manifests/db.pp, line: 56, column: 49)

````

**Comment by trefzer** [comment]
This is not an puppet-postfixadmin issue, you probably have to set mysql::params::exec_path in hiera according to the puppetlabs-mysql  module.
